portfolio/access/urls.py
from django.conf.urls import url
from . import views

app_name = 'access'

urlpatterns = [

    url(r'^access/login/$', views.UserLoginFormView.as_view(), name='login'),

    url(r'^access/logout/$', views.userlogout, name='logout'),

    url(r'^access/create/$', views.UserCreateFormView.as_view(), name='create'),

    url(r'^access/user/$', views.UserDetailsView.as_view(), name='details'),




]

portfolio/base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'

urlpatterns = [

    url(r'^countries/$', views.CountriesView.as_view(), name='countries'),

    url(r'^countries/(?P<pk>[0-9]+)/$', views.CountryView.as_view(), name='country'),

    url(r'^types_of_dishes/$', views.TypesOfDishesView.as_view(), name='types'),

    url(r'^types_of_dishes/(?P<pk>[0-9]+)/$', views.DishesOfTypeView.as_view(), name='dishes'),

    url(r'^dish/(?P<pk>[0-9]+)/$', views.DishView.as_view(), name='dish'),

    url(r'^countries/update/(?P<pk>[0-9]+)/$', views.CountryUpdateView.as_view(), name='country_update'),

    url(r'^dish/update/(?P<pk>[0-9]+)/$', views.DishUpdateView.as_view(), name='dish_update'),


]

portfolio/portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('access.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('base.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



portfolio/base/models.py
from django.contrib.auth.models import User
from django.db import models


class Countries(models.Model):
    name = models.CharField(max_length=256, help_text='max_length=256')
    description = models.CharField(max_length=256, help_text='max_length=256', blank=False)
    img = models.ImageField(upload_to='base/countries/img/')
    flag = models.ImageField(upload_to='base/countries/flag/')

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"

class TypesOfDishes(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None) #type
    main_img = models.ImageField(upload_to='base/type_dish_img/', blank=True, null=True)
    description = models.CharField(max_length=256, help_text='max_length=256', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Type"
        verbose_name_plural = "Types"


class Dish(models.Model):
    name = models.CharField(max_length=256, help_text='max_length=256')
    description = models.CharField(max_length=256, help_text='max_length=256', blank=True)
    main_img = models.ImageField(upload_to='base/dish_img/', blank=True, null=True)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE, null=True)
    type = models.ForeignKey(TypesOfDishes, on_delete=models.CASCADE, null=False, default=None)
    recipe = models.CharField(max_length=2048, help_text='max_length=2048', blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"


class DishImg(models.Model):
    name = models.CharField(max_length=256, help_text='name of picture (name_"img")')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    img = models.ImageField(upload_to='base/dish_img/')

    is_active = models.BooleanField(default=False)
    upload = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"



class Comment(models.Model):
    comment = models.TextField('Comment')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, null=True)

    is_active = models.BooleanField(default=False)
    is_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    is_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.dish

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

portfolio/base/forms.py
from django import forms
from .models import *


class CommentForm(forms.Form):
    comment_area = forms.CharField(label="", widget=forms.Textarea)

portfolio/base/views.py
from django.views.generic import View, DetailView, UpdateView, ListView
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import auth
from .forms import *


class CountriesView(View):
    template_name = 'base/countries.html'
    context_object_name = 'list_of_countries'

    def get(self, request, **kwargs):
        list_of_countries = Countries.objects.all()
        counter = Paginator(list_of_countries, 2)
        page = int(request.GET.get('page', '1'))
        contacts = counter.page(page)
        return render(request, self.template_name, locals())


class CountryView(DetailView):
    model = Countries
    template_name = 'base/country.html'


class CountryUpdateView(UpdateView):
    model = Countries
    template_name = 'base/update_form.html'
    fields = '__all__'


class DishUpdateView(UpdateView):
    model = Dish
    template_name = 'base/update_form.html'
    fields = '__all__'


class DishView(DetailView):
    model = Dish
    template_name = 'base/dish.html'
    form_class = CommentForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['form'] = self.form_class(None)
        return self.render_to_response(context)

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.dish = Dish.objects.get(id=kwargs['pk'])
            comment.user = auth.get_user(request)
            comment.comment = form.cleaned_data['comment_area']
            comment.save()
        return redirect('/dish/'+str(kwargs['pk'])+'/')


class TypesOfDishesView(View):
    template_name = 'base/types_of_dishes.html'
    context_object_name = 'types'

    def get(self, request, **kwargs):
        types = TypesOfDishes.objects.all()
        return render(request, self.template_name, locals())


class DishesOfTypeView(DetailView):
    model = TypesOfDishes
    template_name = 'base/dishes_of_type.html'

portfolio/templates/base/comment_object.html
<div class="">
  <h4>{{ object.user }}: {{ object.comment }}</h4> <p> <br>
</div>

portfolio/templates/base/countries.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Countries {% endblock %}


{% block content %}

<div id="page-content-wrapper" >
    <div class="container-fluid">
        <div class="row">
            {% for contact in contacts %}
                {% include 'base/countries_object.html' %}
            {% endfor %}
        <div class="pagination">
        <span class="step-links">
            {% if contacts.has_previous %}
                <a href="?page={{ contacts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ contacts.number }} of {{ contacts.paginator.num_pages }}.
            </span>

            {% if contacts.has_next %}
                <a href="?page={{ contacts.next_page_number }}">next</a>
            {% endif %}
        </span>
    </div>
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/base/countries_object.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="{{ contact.img.url }}" alt="...">
        <img src="{{ contact.flag.url }}" alt="...">
        <div class="caption">
             <a href="{% url 'base:country' contact.id %}"><h3>{{ contact.name }}</h3></a>
            <p><h3>{{ contact.description }}</h3></p>
            {% if request.session.username == 'admin' %}
                <p><a href="{% url 'base:country_update' contact .id %}" class="btn btn-primary" role="button">Update</a>
            {% else %}
                <a href="{% url 'base:country' contact.id %}">Details</a></p>
            {% endif %}
        </div>
    </div>
</div>

portfolio/templates/base/country.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Country {% endblock %}


{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            {% for object in countries.dish_set.all %}
                <label for="ctr{{forloop.counter}}">
                    {% include 'base/country_object.html' %}
                </label><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/base/country_object.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="{{ object.main_img.url }}" alt="...">
        <div class="caption">
            <a href="{% url 'base:dish' object.id %}"><h3>{{ object.name }}</h3></a>
            <h6>{{ object.price }}$</h6>
            {% if request.session.username == 'admin' %}
                <p><a href="{% url 'base:dish_update' object.id %}" class="btn btn-primary" role="button">Update</a>
            {% else %}
                <a href="{% url 'base:dish' object.id %}">Details</a></p>
            {% endif %}
        </div>
    </div>
</div>

portfolio/templates/base/create.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Create {% endblock %}


{% block content %}
    <div class="col-lg-offset-4 col-lg-4">
    <form action="" method="post" class="form-inline text-center">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}
            {% include 'base/login_obgect.html' %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
    </form>
    </div>
{% endblock %}

portfolio/templates/base/dish.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Dish {% endblock %}


{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <h1>{{ dish.name }}</h1>
        {% for object in dish.dishimg_set.all %}
            <label for="object{{forloop.counter}}">
            <img src="{{ object.img.url }}">
            </label><br>
        {% endfor %}
        <h4>{{ dish.recipe}}</h4>
    <hr>
        {% for object in dish.comment_set.all %}
            {% include 'base/comment_object.html'%}
        {% endfor %}
     <form action="" method="post" class="form-inline text-center">
        <h2 class="form-signin-heading">Comments</h2>
        {% csrf_token %}
         {% for field in form %}
             {{ field }}
         {% endfor %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Post</button>
    </form>
    </div>
</div>


{% endblock %}

portfolio/templates/base/dishes_of_type.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Country {% endblock %}


{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            {% for object in typesofdishes.dish_set.all %}
                <label for="ctr{{forloop.counter}}">
                    {% include 'base/dishes_of_type_object.html' %}
                </label>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/base/dishes_of_type_object.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="{{ object.main_img.url }}" alt="...">
        <div class="caption">
            <a href="{% url 'base:dish' object.id %}"><h3>{{ object.name }}</h3></a>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
    </div>
</div>

portfolio/templates/base/login.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Create {% endblock %}


{% block content %}
  <div class="col-lg-offset-4 col-lg-4">
    <form action="" method="post" class="form-inline text-center">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}
        {% include 'base/login_obgect.html' %}
        {% if login_error %}
            <label class="error"> {{ login_error }}</label>
        {% endif %}
        <button type="submit" class="btn btn-primary btn-orange">Submit</button>
        <label class="center" ><a href="{% url 'base:create'  %}">Create account</a></label>
    </form>
</div>

{% endblock %}

portfolio/templates/base/types_of_dishes.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Country {% endblock %}


{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <div class="row">
            {% for object in types %}
                <label for="ctr{{forloop.counter}}">
                    {% include 'base/types_of_dishes_object.html' %}
                </label><br>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

portfolio/templates/base/types_of_dishes_object.html
<div class="col-sm-6 col-md-4">
    <div class="thumbnail">
        <img src="{{ object.main_img.url }}" alt="...">
        <div class="caption">
            <a href="{% url 'base:dishes' object.id %}"><h3>{{ object.name }}</h3></a>
            <h6>{{ object.description}}</h6>
            <p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
        </div>
    </div>
</div>

portfolio/templates/base/update_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12  col-md-7">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    <div class="col-sm-offset-2 col-sm-10">
                                        <span class="text-danger small"> {{ field.errors }} </span>
                                    </div>
                                    <label class="control-label col-sm-2">{{ field.label_tag }} </label>
                                    <div class="col-sm-10"> {{ field }}</div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}