portfolio/access/urls.py
from django.conf.urls import url
from . import views

app_name = 'access'

urlpatterns = [

    url(r'^access/login/$', views.UserLoginFormView.as_view(), name='login'),

    url(r'^access/logout/$', views.userlogout, name='logout'),

    url(r'^access/create/$', views.UserCreateFormView.as_view(), name='create'),

    url(r'^access/user/$', views.UserDetailsView.as_view(), name='details'),




]

portfolio/base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'

urlpatterns = [

    url(r'^countries/$', views.CountriesView.as_view(), name='countries'),

    url(r'^countries/(?P<pk>[0-9]+)/$', views.CountryView.as_view(), name='country'),

    url(r'^types_of_dishes/$', views.TypesOfDishesView.as_view(), name='types'),

    url(r'^types_of_dishes/(?P<pk>[0-9]+)/$', views.DishesOfTypeView.as_view(), name='dishes'),

    url(r'^dish/(?P<pk>[0-9]+)/$', views.DishView.as_view(), name='dish'),

    url(r'^countries/update/(?P<pk>[0-9]+)/$', views.CountryUpdateView.as_view(), name='country_update'),

    url(r'^dish/update/(?P<pk>[0-9]+)/$', views.DishUpdateView.as_view(), name='dish_update'),


]

portfolio/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.home, name='home'),

    url(r'^news', views.NewsView.as_view(), name='news'),


]

portfolio/portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('access.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('base.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



portfolio/base/models.py
from django.contrib.auth.models import User
from django.db import models


class Countries(models.Model):
    name = models.CharField(max_length=256, help_text='max_length=256')
    description = models.CharField(max_length=256, help_text='max_length=256', blank=False)
    img = models.ImageField(upload_to='base/countries/img/')
    flag = models.ImageField(upload_to='base/countries/flag/')

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Country"
        verbose_name_plural = "Countries"

class TypesOfDishes(models.Model):
    name = models.CharField(max_length=64, blank=True, null=True, default=None) #type
    main_img = models.ImageField(upload_to='base/type_dish_img/', blank=True, null=True)
    description = models.CharField(max_length=256, help_text='max_length=256', blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Type"
        verbose_name_plural = "Types"


class Dish(models.Model):
    name = models.CharField(max_length=256, help_text='max_length=256')
    description = models.CharField(max_length=256, help_text='max_length=256', blank=True)
    main_img = models.ImageField(upload_to='base/dish_img/', blank=True, null=True)
    country = models.ForeignKey(Countries, on_delete=models.CASCADE, null=True)
    type = models.ForeignKey(TypesOfDishes, on_delete=models.CASCADE, null=False, default=None)
    recipe = models.CharField(max_length=2048, help_text='max_length=2048', blank=True, null=True, default=None)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

    is_active = models.BooleanField(default=True)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Dish"
        verbose_name_plural = "Dishes"


class DishImg(models.Model):
    name = models.CharField(max_length=256, help_text='name of picture (name_"img")')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    img = models.ImageField(upload_to='base/dish_img/')

    is_active = models.BooleanField(default=False)
    upload = models.DateTimeField(auto_now_add=True, auto_now=False)

    def __str__(self):
        return "%s" % self.name

    class Meta:
        verbose_name = "Image"
        verbose_name_plural = "Images"



class Comment(models.Model):
    comment = models.TextField('Comment')
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(User, null=True)

    is_active = models.BooleanField(default=False)
    is_created = models.DateTimeField(auto_now_add=True, auto_now=False)
    is_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

    def __str__(self):
        return "%s" % self.dish

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"

portfolio/base/forms.py
from django import forms
from .models import *


class CommentForm(forms.Form):
    comment_area = forms.CharField(label="", widget=forms.Textarea)

portfolio/base/views.py
from django.views.generic import View, DetailView, UpdateView, ListView
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import auth
from .forms import *


class CountriesView(View):
    template_name = 'base/countries.html'
    context_object_name = 'list_of_countries'

    def get(self, request, **kwargs):
        list_of_countries = Countries.objects.all()
        counter = Paginator(list_of_countries, 2)
        page = int(request.GET.get('page', '1'))
        contacts = counter.page(page)
        return render(request, self.template_name, locals())


class CountryView(DetailView):
    model = Countries
    template_name = 'base/country.html'


class CountryUpdateView(UpdateView):
    model = Countries
    template_name = 'base/update_form.html'
    fields = '__all__'


class DishUpdateView(UpdateView):
    model = Dish
    template_name = 'base/update_form.html'
    fields = '__all__'


class DishView(DetailView):
    model = Dish
    template_name = 'base/dish.html'
    form_class = CommentForm

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context['form'] = self.form_class(None)
        return self.render_to_response(context)

    def post(self, request, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            comment = Comment()
            comment.dish = Dish.objects.get(id=kwargs['pk'])
            comment.user = auth.get_user(request)
            comment.comment = form.cleaned_data['comment_area']
            comment.save()
        return redirect('/dish/'+str(kwargs['pk'])+'/')


class TypesOfDishesView(View):
    template_name = 'base/types_of_dishes.html'
    context_object_name = 'types'

    def get(self, request, **kwargs):
        types = TypesOfDishes.objects.all()
        return render(request, self.template_name, locals())


class DishesOfTypeView(DetailView):
    model = TypesOfDishes
    template_name = 'base/dishes_of_type.html'

portfolio/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>{% block titel %}Titel{% endblock %}</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,400" rel="stylesheet">
        <link href="{% static 'css/style.css'%}" rel="stylesheet">
        <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">
    </head>


    <body>
            <div class="content">
                    {% include 'navbar.html' %}
                <div class="container">
                    <div class="row">
                        {% block content %}


                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>

            <!-- jQuery -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


        <script src="{% static 'js/side_navbar.js' %}"></script>
        <script src="{% static 'js/user_details.js' %}"></script>


    </body>
</html>

portfolio/templates/footer.html
<!--    <footer class="footer">
      <div class="container-fluid">
        <p class="text-muted">Footer</p>
      </div>
</footer> -->

portfolio/templates/navbar.html
<nav class="navbar navbar-inverse">
    <div class="navbar-header">
        <div class="container-fluid">
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#menu-toggle" class="btn btn-secondary" id="menu-toggle">Menu</a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                      <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <button id="user_details" class="btn dropdown-toggle glyphicon glyphicon-user">{{ request.session.username }}
                        </button>
                        <ul id="user_details_list" class="dropdown-menu">
                            <li>
                                <a href="{% url 'access:details' %}">User Account</a>
                            </li>
                            <li>
                                {% if request.session.username %}
                                    <a href="{% url 'access:logout' %}">Log out</a>
                                {% else %}
                                    <a href="{% url 'access:login' %}">Log in</a>
                                {% endif %}
                            </li>
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
</nav>

<div id="wrapper">
    <div id="sidebar-wrapper">
                <ul class="sidebar-nav">
                    <li>
                        <a href="{% url 'home:home' %}">Delicia</a>
                    </li>
                    <li>
                        <a href="{% url 'home:news' %}">News</a>
                    </li>
                    <li>
                        <a href="{% url 'base:countries' %}">Countries</a>
                    </li>
                    <li>
                        <a href="{% url 'base:types' %}">Food</a>
                    </li>
                    <li>
                        <a href="#">Gallery</a>
                    </li>
                    <br>
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                    <li>
                    </li>
                </ul>
    </div>