portfolio/access/urls.py
from django.conf.urls import url
from . import views

app_name = 'access'

urlpatterns = [

    url(r'^access/login/$', views.UserLoginFormView.as_view(), name='login'),

    url(r'^access/logout/$', views.userlogout, name='logout'),

    url(r'^access/create/$', views.UserCreateFormView.as_view(), name='create'),

    url(r'^access/user/$', views.UserDetailsView.as_view(), name='details'),




]

portfolio/base/urls.py
from django.conf.urls import url
from . import views

app_name = 'base'

urlpatterns = [

    url(r'^countries/$', views.CountriesView.as_view(), name='countries'),

    url(r'^countries/(?P<pk>[0-9]+)/$', views.CountryView.as_view(), name='country'),

    url(r'^types_of_dishes/$', views.TypesOfDishesView.as_view(), name='types'),

    url(r'^types_of_dishes/(?P<pk>[0-9]+)/$', views.DishesOfTypeView.as_view(), name='dishes'),

    url(r'^dish/(?P<pk>[0-9]+)/$', views.DishView.as_view(), name='dish'),

    url(r'^countries/update/(?P<pk>[0-9]+)/$', views.CountryUpdateView.as_view(), name='country_update'),

    url(r'^dish/update/(?P<pk>[0-9]+)/$', views.DishUpdateView.as_view(), name='dish_update'),


]

portfolio/portfolio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('access.urls')),
    url(r'^', include('home.urls')),
    url(r'^', include('base.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



portfolio/access/models.py
from django.db import models
from django.contrib.auth.models import User


class Moderator(User):
    user = models.OneToOneField(User)
    front_end = models.CharField(max_length=128)

portfolio/access/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *


class UserCreateForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)
    email = models.EmailField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email',  'password']




class UserLoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username',  'password']

portfolio/access/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from django.contrib import auth, sessions
from django.views.generic import View, DetailView
from .forms import *


class UserDetailsView(View):
    model = User
    template_name = 'access/user_details.html'

    def get(self, request):
        temp = self.template_name
        return render(request, temp, locals())


class UserCreateFormView(View):
    form_class = UserCreateForm
    template_name = 'access/create.html'

    def get(self, request):
        temp = self.template_name
        form = self.form_class(None)
        return render(request, temp, {'form': form})

    def post(self, request):
        temp = self.template_name
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    request.session.set_expiry(3600)
                    request.session['username'] = username
                    login(request, user)
                    return redirect('home:home')

        return render(request, temp, {'form': form})


class UserLoginFormView(View):
    form_class = UserLoginForm
    template_name = 'access/login.html'

    def get(self, request, **kwargs):
        username = auth.get_user(request)
        form = self.form_class(None)
        return render(request, self.template_name, locals())

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active and username not in request.session:
                login(request, user)
                request.session.set_expiry(3600)
                request.session['username'] = username

                return redirect('home:home')
        else:
            login_error = "User dose not exist"
            form = self.form_class(None)
            return render(request, self.template_name, locals())


def userlogout(request):
    auth.logout(request)
    return redirect('/')

portfolio/templates/access/create.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Create {% endblock %}


{% block content %}
    <div class="col-lg-offset-4 col-lg-4">
    <form action="" method="post" class="form-inline text-center">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}
            {% include 'access/login_obgect.html' %}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
    </form>
    </div>
{% endblock %}

portfolio/templates/access/login.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} Create {% endblock %}


{% block content %}
  <div class="col-lg-offset-4 col-lg-4">
    <form action="" method="post" class="form-inline text-center">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% csrf_token %}
        {% include 'access/login_obgect.html' %}
        {% if login_error %}
            <label class="error"> {{ login_error }}</label>
        {% endif %}
        <button type="submit" class="btn btn-primary btn-orange">Submit</button>
        <label class="center" ><a href="{% url 'access:create'  %}">Create account</a></label>
    </form>
</div>

{% endblock %}

portfolio/templates/access/login_obgect.html
{% for field in form %}
    <div>
        <label class="control-label col-lg-8">{{ field.label_tag }} </label>
        {{ field }}
    </div>
{% endfor %}

portfolio/templates/access/user_details.html
{% extends 'base.html' %}
{% load static %}

{% block titel %} User {% endblock %}


{% block content %}

<div id="page-content-wrapper">
    <div class="container-fluid">
        <h1> Username:{{ user.username }}</h1>
        <h3>First Name:{{ user.first_name }}</h3>
        <h5>Last Name:{{ user.last_name }}</h5>
        <h5>Email:{{ user.email }}</h5>


    </div>
</div>


{% endblock %}